# Base directory to store all task outputs
base_dir: "/scratch/data/edgar/above200B/"

################
# DATA PARSING #
################

DataParsing:
  path_to_data_folders: "/cluster/edgar_filings_above$200B"
  entity_prefixes: ["us-gaap"]
  entity_formats: ["ixt:numdotdecimal", "ix:nonFraction"]
  dataset_name: "EDGAR"
  debug_size: null


#####################
# DATA TOKENIZATION #
#####################

DataTokenizing:
  remove_tables: true
  language: &language "en"


################
# DATA TAGGING #
################

DataTagging:
  remove_non_currency_sentences: true
  language: *language


#####################
# Annotation Merger #
#####################

AnnotationMerging:
  excel_annotation_file: "/scratch/projects/edgar/data/edgar_relation_annotations.xlsx"
  filter_for_annotated_docs: true  # set false for self-training
  ignore_noncritical_warnings: true
  skip_sentences_with_error: true
  merge_auto_annotations: false
  label_mapping:
    kpi: 'kpi'
    kpi_coref: 'kpi_coref'
    cy: 'cy'
    py: 'py'
    py1: "py1"
    increase: 'increase'
    increase_py: "increase_py"
    decrease: 'decrease'
    decrease_py: "decrease_py"
    thereof: 'thereof'
    thereof_coref: 'thereof'
    attr: "attr"
    thereof_cy: 'cy'
    thereof_py: 'py'
    davon_increase: false
    davon_decrease: false
    false_positive: false

#####################
# SubWord Tokenization #
#####################

SubWordTokenization:
  tokenizer_name: 'bert-base-uncased' # '&tokname 'bert-base-german-dbmdz-cased'
  special_tokens: null
#    additional_special_tokens : [['[NUM]']]