# Base directory to store all task outputs
base_dir: "/scratch/data/edgar/debug_1/"

################
# DATA PARSING #
################

DataParsing:
  path_to_data_folders: "/cluster/edgar_filings_20largest"
  entity_prefixes: ["us-gaap"]
  entity_formats: ["ixt:numdotdecimal", "ix:nonFraction"]
  dataset_name: "EDGAR"
  debug_size: 10


#####################
# DATA TOKENIZATION #
#####################

DataTokenizing:
  remove_tables: true
  language: &language "en"


################
# DATA TAGGING #
################

DataTagging:
  remove_non_currency_sentences: true
  language: *language
